name: Update docs
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'

    - name: Install mkdocs
      run: sudo pip install mkdocs

    - name: Install MkDocs theme
      run: sudo pip install mkdocs-material==3.1.0

    - name: Avoid hosts unknown for github
      run: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

    - name: Build docs
      run: cd docs/documentation && mkdocs gh-deploy
